### ISSUE TITLE
Top Header

### ISSUE THREAD

**Issue by Moniy0o0** [sayyah/GuilanRice#2]
**Describe the solution you'd like**
گذاشتن ایمیل و شماره تلفن
بقیه موارد نیاز نیست
![image](https://github.com/sayyah/ECommerce/assets/32224766/df6c77f7-c5ac-435f-af47-55d59c363b14)

**Comment by AmdRzaM** [comment]
فقط لوگوهای سایت اصلی رو نتونستم دانلود کنم دانلود بشه عوض میکنم

**Comment by Moniy0o0** [comment]
من هدری در سایت نمیبینم
اگه اوکی هست تسک تاپ هدر 
لطفا عکس نتیجه کار رو بفرستین

**Comment by AmdRzaM** [comment]
یک کد اشتباه داخلش بود درستش کردم الان معلوم هست
