### ISSUE TITLE
SlideShow Header

### ISSUE THREAD

**Issue by Moniy0o0** [sayyah/GuilanRice#3]
**Describe the solution you'd like**
گذاشتن 3 اسلاید شو و تعبیه افکت zoom-in و zoom-out

**Comment by AmdRzaM** [comment]
لینک ثبت شد

**Comment by sayyah** [comment]
کانفلیکت داره

**Comment by AmdRzaM** [comment]
حل شد

**Comment by Moniy0o0** [comment]
![Image](https://github.com/sayyah/GuilanRice/assets/32224766/88f03d3a-0940-4c25-8c8c-cd8936e4e225)

اسلاید شو از زیر فوتر بیرون زده

**Comment by AmdRzaM** [comment]
در حال کار کردن روش هستم

**Comment by AmdRzaM** [comment]
افکت زوم رو هنوز نتونستم انجام بدم

**Comment by AmdRzaM** [comment]
خود اسلایدشو با افکت زوم درست شد
