### ISSUE TITLE
Text On SlideShow

### ISSUE THREAD

**Issue by Moniy0o0** [sayyah/GuilanRice#4]
**Describe the solution you'd like**
نوشتن متن روی تمام اسلایدشو ها 
و قرار دادن 2 دکمه مربوطه

**Comment by AmdRzaM** [comment]
داخل تسک ۳ اسلایدشو انجام شد

**Comment by AmdRzaM** [comment]
متن ها درست شده بود و دکمه ها گذاشته شده ولی بخاطر مشکل اسایدشو درست کار نمیکنن

**Comment by AmdRzaM** [comment]
کد رو از اول نوشتم و نمیدونم چرا هیچ چیز رو داخل اسلایدشو نشون نمیده
برای کمک گرفتن ارسالش کردم که مشکل رو پیدا کنیم
