### ISSUE TITLE
Taste Rice

### ISSUE THREAD

**Issue by Moniy0o0** [sayyah/GuilanRice#9]
**Describe the solution you'd like**
قسمت بالای فوتر 

![image](https://github.com/sayyah/ECommerce/assets/32224766/71d8c7a5-ff57-41b4-bbd2-8399a4677785)

**Comment by Mahyar-ssh** [comment]
سلام خسته نباشید
نتونستم مشکل کد تسک برطرف کنم در جای خودش قراربدم چندتا کد رسپاسیو نوشتم ولی باز عمل نکرد
  بی زحمت مشاهده میکنید و نظرتون میدین

**Comment by Moniy0o0** [comment]
راهنمایی انجام شده
دوباره تلاش کنید
